---
name: Timeout-Queue
version: 1.02
author:
  - 'Troels Liebe Bentsen <troels@infopro.dk>'
abstract: A priority queue made for handling timeouts
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
provides:
  Timeout::Queue:
    file: lib/Timeout/Queue.pm
    version: 1.02
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
